### ISSUE TITLE
[Note] I ported the decompressor to 8086 assembly

### ISSUE THREAD

**Issue by ecm-pushbx** [xbarin02/wt-compressor#1]
You can find the source at https://hg.ulukai.org/ecm/inicomp/file/1229f30865d2/x.asm

As noted [in the initial commit](https://hg.ulukai.org/ecm/inicomp/rev/6abaa4e4c065) it is based on [git 71afd5b05eb4](https://github.com/xbarin02/x-compressor/commit/71afd5b05eb43b17c5564d8a11670027d3387038).

To save on the memory usage, I limited the ctFreq field to 16 bits. (Carry out of the top bit is detected as an error.) Even so, the context tables require 256 KiB. I also had to add [some layer threshold memory](https://hg.ulukai.org/ecm/rxdos-7.2x/rev/59c04b5e8f13) (the word "layout" here is in error) so there's enough space to decompress subsequent layers. (The 96 kB kernel compresses to 62 kB and uses two layers.)

I did not yet inline function calls only used once. However, I do not expect much speed-up from that. I also did not yet add support for overlapping source and destination, which all four of the other decompressors do support.

Its speed seems to place it as the slowest of all five decompressors yet. I think the reason for that is that every byte has to call into bio_read_gr, increment_frequency, and update_model. I was able to modify/create all other (mostly LZ-like) decompressors to use repeated string instructions to write several literal or match bytes in one step.

It is also the first decompressor to need additional memory (other than stack frame variables). And the compression ratio is not especially good either. However, the port was interesting to me. Thanks for your work!

**Comment by xbarin02** [comment]
Wow, I didn't expect anyone to do such a thing :)

Basically, the (de)compressor is optimized for good readability and brevity of the code. If you want to optimize it for speed, I recommend making the following algorithmic changes first: (1) Do not recalculate the `increment_frequency()` for every symbol, call this function only once per `RESET_INTERVAL`. The impact on compression ratio is small. The speed-up is substantial. (2) Do not call the `update_model()` at all, fix the `opt_k = 3`. The impact on compression ratio is small as well. (3) Focus on the `bio_read_bits()`, this one is critical. Replace bit-masking `2^s - 1` with `0xffffffff >> (32 - n)`. Drop the `struct bio` (indirect memory access), keep the `b`, `c`, and `ptr` in registers. Replace 32-bit bit buffer `b` with 64-bit one (less memory accesses). An so on...

Anyway you have my big respect!

**Comment by xbarin02** [comment]
Also, if you wan to save the memory usage, select the context as `context = table + (c & 95);`. This will reduce the number of contexts to 64 (instead of 256), while it has only a little effect on the compression factor.

**Comment by ecm-pushbx** [comment]
> If you want to optimize it for speed,

Actually I tend to optimise for size first, meaning size of the final file (compressed data + decompressor stub), size of memory needed for decompression, and size of the source code.

> Do not recalculate the `increment_frequency()` for every symbol, call this function only once per `RESET_INTERVAL`. The impact on compression ratio is small. The speed-up is substantial. 

I don't understand how that is supposed to work. From what I do understand, though, it would create an incompatible format to your implementation.

> (2) Do not call the `update_model()` at all, fix the `opt_k = 3`. The impact on compression ratio is small as well.

This would definitely create an incompatible format. I'm looking to keep using the original toolchain's format so that I can use your unmodified application [to do the compressing](https://hg.ulukai.org/ecm/rxdos-7.2x/file/59c04b5e8f13/mak.sh#l246) then use that as my payload.

> (3) Focus on the `bio_read_bits()`, this one is critical. Replace bit-masking `2^s - 1` with `0xffffffff >> (32 - n)`.

The `2**s - 1` is just `(1 << s) - 1` so I do not expect any difference from this.

> Drop the `struct bio` (indirect memory access), keep the `b`, `c`, and `ptr` in registers.

Parts of the decompressor already have high pressure on the 8086's six 16-bit GPRs, so I can't keep the 32-bit `b` (`bit_buffer`) or (8-bit) `c` (`bit_counter`) in registers. Likewise for the 16:16 (far) `?src` pointer. I did drop the struct in favour of keeping these variables in the `depack` function's stack frame though; most of the functions do not create their own stack frame and instead access the main `depack` frame (input `ss:bp` is kept for the subfunctions).

Considering this I might be able to keep `?src` in registers at most times but I would have to preserve `si` across the parts where I use it as a GPR. Matches that copy data from earlier in the decompressed window don't exist for this format, so we wouldn't have to do anything to preserve the pointer across those.

> Replace 32-bit bit buffer `b` with 64-bit one (less memory accesses).

Also incompatible, and would double the handling for shifting and masking from the variable.

> Also, if you wan to save the memory usage, select the context as `context = table + (c & 95);`. This will reduce the number of contexts to 64 (instead of 256), while it has only a little effect on the compression factor.

Though also incompatible, this is interesting. Why mask with 95? How does that lead to 64 contexts?

**Comment by ecm-pushbx** [comment]
Ah, 95 is 5Fh, which has 6 bits set. I think to make that into an index into a 64-contexts table we'd need some bitshifting though. Why not mask with 63 (= 3Fh) ?

**Comment by xbarin02** [comment]
Yes, that would create an incompatible format. Sorry, I thought you didn't mind this.

To that magic number 95: The compressor uses context modeling which uses a single previous byte in the uncompressed stream to predict the next byte. This approach is especially powerful when compression English texts (like the enwik8 reference file). Now, if you look at the ASCII table (say [this one](http://www.asciitable.com/)), you can see that lowercase letters differ from uppercase letters in 0x20 bit set. Moreover, the English alphabet is encoded in least significant seven bits of that table. Therefore merging these context almost doesn't affect the compression ratio, while substantially reducing the number of contexts used. This is especially true on text files, however, it works well on any data.
